name: CD

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: 🐙 Generate new release
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - name: ⬇️ Checkout project
        uses: actions/checkout@v2

      - name: 📋 Build Changelog
        run: npx extract-changelog-release > RELEASE_BODY.md

      - name: 🍻 Build and generate new release
        uses: softprops/action-gh-release@v1
        with:
          body_path: RELEASE_BODY.md
          token: ${{ secrets.GITHUB_TOKEN }}

  distribute:
    name: 🛩️ Deliver project
    runs-on: ubuntu-latest
    needs: release

    steps:
      - name: ⬇️ Checkout project
        uses: actions/checkout@v2

      - name: 🏷️ Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: 💽 Build OCI image
        run: make build/ssr TAG=${{ steps.get_version.outputs.VERSION }}
